### ISSUE TITLE
Tag v1.0.1 as the latest release?

### ISSUE THREAD

**Issue by carlocab** [aaronjanse/3mux#108]
I've submitted 3mux for packaging in Homebrew (cf. #88).

However your latest release (v0.3.0) on GitHub doesn't build for me on Big Sur. v1.0.1 does, but it's currently listed as a pre-release.

Could you please tag v1.0.1 as the latest release, so that 3mux can be accepted into Homebrew? Thanks!

Homebrew PR: https://github.com/Homebrew/homebrew-core/pull/72093

**Comment by aaronjanse** [comment]
Exciting!

PR #101 should significantly improve 3mux efficiency. Once that's merged (hopefully very soon) I'll make sure to tag an official GitHub release and leave a comment in this issue.

I'll make sure to make versions tags in the future work better with package managers

**Comment by PotatoParser** [comment]
Planning to tag a release version soon! ([v1.1.0](https://github.com/aaronjanse/3mux/releases))

**Comment by carlocab** [comment]
Thanks, @aaronjanse, @PotatoParser!
