### ISSUE TITLE
Hardcoded Shell

### ISSUE THREAD

**Issue by DavidBuchanan314** [aaronjanse/3mux#12]
By default, the shell binary is hardcoded to `zsh`.

https://github.com/aaronjanse/3mux/blob/9068500789c16e5ae7ba83ff920cc94bc74b4cbf/shell.go#L23

I don't have `zsh` installed on my machine, resulting in a silent failure. Or, if logging to a file is enabled:

```
2020/04/11 18:27:11 exec: "zsh": executable file not found in $PATH
```

Might I suggest that the current shell is read via the `$SHELL` environment variable?

**Comment by maxmcd** [comment]
I get strange issues when switching to `bash`, would be great to hear what the story is with support for other shells

**Comment by aaronjanse** [comment]
> I get strange issues when switching to bash, would be great to hear what the story is with support for other shells

Weird. I've tested equally on zsh and bash. Would you mind documenting your issues in https://github.com/aaronjanse/3mux/issues/15?
