### ISSUE TITLE
Alt+Enter opens a pane, not a window

### ISSUE THREAD

**Issue by dkvasnicka** [aaronjanse/3mux#18]
Are you using a different terminology compared to tmux or is this a bug? Do you plan to implement "tab-like" windows like tmux with panes inside them? (and group them into sessions, which you already have an issue open here?)

**Comment by aaronjanse** [comment]
I'm using different terminology. I'll update the README to say "pane" (which I use internally).

**Comment by aaronjanse** [comment]
> Do you plan to implement "tab-like" windows like tmux with panes inside them?
I do plan to implement this

**Comment by aaronjanse** [comment]
Fixed by https://github.com/aaronjanse/3mux/commit/31b1c44d5ae7d9608a000d1dc2514828542b6d49. Tabs tracked at https://github.com/aaronjanse/3mux/issues/32
