### ISSUE TITLE
thanks for bring sanity to a terminal multiplexer - and a minor suggestion

### ISSUE THREAD

**Issue by HouzuoGuo** [aaronjanse/3mux#23]
Very well done - you brought both functionality and usability to a next-generation terminal multiplexer, I was a long term tmux user, 3mux works far better out of the box!

By the way, a minor suggestion - alt+b and alt+f are used by readline for moving cursor between words, they're very handy as many terminal emulators out there don't correctly handle ctrl+left/right for the same feature. Would you consider using a different default key for making a panel full screen?

Another odd one, I'm using fish on Ubuntu 18.04, this happens to fish when I repeatedly press enter in 3mux:

![image](https://user-images.githubusercontent.com/563872/79096519-18892a00-7d66-11ea-81e2-d2b39a21bd31.png)

**Comment by aaronjanse** [comment]
Would you mind running `3mux --log` then sending ./logs.txt?

**Comment by HouzuoGuo** [comment]
Here it is:

<pre>
howard@hzgl-dev-ubuntu ~> cat logs.txt
2020/04/13 16:28:50 HARD REFRESH
2020/04/13 16:28:50 Unrecognized escape code:
2020/04/13 16:28:50 Unrecognized escape code:
2020/04/13 16:28:51 Unrecognized escape code:
2020/04/13 16:28:51 Unrecognized escape code:
2020/04/13 16:28:51 Unrecognized escape code:
2020/04/13 16:28:51 Unrecognized escape code:
2020/04/13 16:28:51 Unrecognized escape code:
2020/04/13 16:28:51 Unrecognized escape code:
2020/04/13 16:28:51 Unrecognized escape code:
2020/04/13 16:28:51 Unrecognized escape code:
2020/04/13 16:28:51 Unrecognized escape code:
2020/04/13 16:28:51 Unrecognized escape code:
2020/04/13 16:28:51 Unrecognized escape code:
2020/04/13 16:28:51 Unrecognized escape code:
2020/04/13 16:28:51 Unrecognized unprintable rune: 7
2020/04/13 16:28:52 Unrecognized escape code:
2020/04/13 16:28:52 Unrecognized escape code:
2020/04/13 16:28:53 failed to kill term process os: process already finished
</pre>

The terminal emulator is windows terminal 0.9.0, and keyboard repeat rate (windows) is about 20 keys/second, quite fast.

**Comment by aaronjanse** [comment]
> Would you consider using a different default key for making a panel full screen?

Would <kbd>ctrl+shift+f</kbd> work?

> this happens to fish when I repeatedly press enter in 3mux

Would you update 3mux using `get -u github.com/aaronjanse/3mux` then see if you still have this issue? I also noticed that fish path autocomplete is acting weird, which is tracked at https://github.com/aaronjanse/3mux/issues/29

**Comment by HouzuoGuo** [comment]
It works, well done!

**Comment by HouzuoGuo** [comment]
About the shortcut for going full screen with a panel - coincidentally many terminal emulators use ctrl+shift+f for the search feature. How about ctrl+alt+f?

**Comment by aaronjanse** [comment]
Oh, oops! I meant <kbd>alt+shift+f</kbd>. Would that work?

**Comment by HouzuoGuo** [comment]
that sounds good!

**Comment by aaronjanse** [comment]
Thank you for the bug report! Please feel free to comment here or open another issue if you notice anything else weird or have a feature idea!
