### ISSUE TITLE
Create a versioned tag (release) on GitHub

### ISSUE THREAD

**Issue by filalex77** [aaronjanse/3mux#26]
This would greatly help in maintaining packages for `3mux` in repositories like AUR and `nixpkgs` (see [my PR to `NixOS/nixpkgs`](https://github.com/NixOS/nixpkgs/pull/85141).
`v0.1` would do. Thank you for your work!

**Comment by aaronjanse** [comment]
Done! The tag is `v0.1.0`. Thank you!

**Comment by aaronjanse** [comment]
Excited to see this on NixOS!
