### ISSUE TITLE
termbox is no longer maintained.

### ISSUE THREAD

**Issue by doronbehar** [aaronjanse/3mux#27]
https://github.com/aaronjanse/3mux/blob/433d7dbcb12b77142f73c567b8558a06e756e5bf/main.go#L15

FYI, termbox is no longer maintained, see https://github.com/nsf/termbox-go/commit/ed2200f31832eae5a7c3f22738f620fb9c5eda3a , [tcell](https://github.com/gdamore/tcell) is a recommended replacement.

**Comment by aaronjanse** [comment]
I have a branch [0] that uses tcell. The problem is that, as far as I can tell, there is no provided interface for using the terminal's default color palette. Maybe I'm wrong? I hope I'm wrong.

[0] https://github.com/aaronjanse/3mux/tree/tcell

**Comment by aaronjanse** [comment]
Nevermind. https://github.com/gdamore/tcell/issues/308 suggests that using the terminal's default color palette is possible.

**Comment by aaronjanse** [comment]
Thanks for the heads up! I've removed termbox as a dependency :+1:
