### ISSUE TITLE
tmux bindings are buggy

### ISSUE THREAD

**Issue by ghazninattarshah** [aaronjanse/3mux#36]
Error during: pane.go (vt.ProcessStream)
runtime error: index out of range [-1]
Tiling state: Universe[0](Workspace(HSplit[0](Term[181x48]*, Term[-1x48])))
goroutine 38 [running]:
runtime/debug.Stack(0x1183000, 0xc00000e018, 0xc000144a88)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/debug/stack.go:24 +0x9d
main.fatalShutdownNow(0xc001c64140, 0x41)
	/Users/ghazni/go/src/github.com/aaronjanse/3mux/main.go:125 +0x16c
main.newTerm.func4.1()
	/Users/ghazni/go/src/github.com/aaronjanse/3mux/pane.go:112 +0xb3
panic(0x11463e0, 0xc000ef2380)
	/usr/local/Cellar/go/1.14/libexec/src/runtime/panic.go:967 +0x15d
github.com/aaronjanse/3mux/vterm.(*VTerm).handleEraseInDisplay(0xc0001b2000, 0x0, 0x0)
	/Users/ghazni/go/src/github.com/aaronjanse/3mux/vterm/csi.go:171 +0x38c
github.com/aaronjanse/3mux/vterm.(*VTerm).handleCSISequence(0xc0001b2000)
	/Users/ghazni/go/src/github.com/aaronjanse/3mux/vterm/csi.go:87 +0x6e7
github.com/aaronjanse/3mux/vterm.(*VTerm).handleEscapeCode(0xc0001b2000)
	/Users/ghazni/go/src/github.com/aaronjanse/3mux/vterm/stream.go:130 +0x158
github.com/aaronjanse/3mux/vterm.(*VTerm).ProcessStream(0xc0001b2000)
	/Users/ghazni/go/src/github.com/aaronjanse/3mux/vterm/stream.go:80 +0x35f
main.newTerm.func4(0xc0001b2000)
	/Users/ghazni/go/src/github.com/aaronjanse/3mux/pane.go:115 +0x4d
created by main.newTerm
	/Users/ghazni/go/src/github.com/aaronjanse/3mux/pane.go:109 +0x1f5

**Comment by aaronjanse** [comment]
> `Tiling state: Universe[0](Workspace(HSplit[0](Term[181x48]*, Term[-1x48])))`

Oh that's weird. The second terminal claims to have a width of `-1`. Do you have any tips for what keys need to pressed after starting 3mux to cause this panic?

**Comment by ynigun** [comment]
I got a similar error
`error during: pane.go (vt.ProcessStream)
runtime error: index out of range [-1]
Tiling state: Universe[0](Workspace(HSplit[0](VSplit[0](Term[211x55]), Term[-1x55])))
`
This happened after I created a new pane
Then I chose the pane on the left, with the command "Alt + ←"
Then I tried to split vertically
With the command "Ctrl + b+%"
And I got an error

**Comment by aaronjanse** [comment]
I've pushed some commits to master that should fix this. I'm currently refactoring window management in the `dev` branch to prevent this type of bug

**Comment by aaronjanse** [comment]
This should be fixed with `v0.2.0` on `master` :tada:

**Comment by aaronjanse** [comment]
Fixed in `v0.3.0`.
