### ISSUE TITLE
Feature suggestion: Built-in help

### ISSUE THREAD

**Issue by stammon** [aaronjanse/3mux#44]
It would be nice to have a keybinding that creates a new pane, that has the readme/manpage for 3mux open.

Additionally it would be nice to have a bar showing the most common needed keybindings at the bottom, like nano. The visibility of this bar should be configurable.

**Comment by aaronjanse** [comment]
Brilliant. Yes, I definitely think this should be done. Thank you for the suggestion

**Comment by aaronjanse** [comment]
Any thoughts?

![image](https://user-images.githubusercontent.com/16829510/79807782-c1b0c100-8320-11ea-9784-7c853c860d45.png)

**Comment by aaronjanse** [comment]
Fixed in `v0.3.0`.
