### ISSUE TITLE
Error on mac os catalina

### ISSUE THREAD

**Issue by dimm0** [aaronjanse/3mux#5]
```
  ~ go get github.com/aaronjanse/3mux
# github.com/aaronjanse/3mux
go/src/github.com/aaronjanse/3mux/shell.go:96:11: undefined: pty.Setsize
go/src/github.com/aaronjanse/3mux/shell.go:96:32: undefined: pty.Winsize
```

**Comment by dimm0** [comment]
Now works

**Comment by Gys** [comment]
I had exactly the same problem just now. What did you do solve this?

**Comment by aaronjanse** [comment]
Could you tell me the output of `(cd $GOPATH/src/github.com/kr/pty ; git rev-parse HEAD)`?

**Comment by Gys** [comment]
Sure, I have `67e2db24c831afa6c64fc17b4a143390674365ef`

**Comment by aaronjanse** [comment]
3mux now uses go modules. Could you try updating with `go get -u github.com/aaronjanse/3mux`?

**Comment by Gys** [comment]
Yes, working now! Thank you!

**Comment by aaronjanse** [comment]
Awesome! Thanks for helping me figure out the issue by running that git command!
