### ISSUE TITLE
How to restore the session?

### ISSUE THREAD

**Issue by kafran** [aaronjanse/3mux#52]
How do I restore the session? `3mux ls` and `3mux attach` doesn't seems to work.

**Comment by aaronjanse** [comment]
:-( This has not yet implemented, but will be soon #11

**Comment by kafran** [comment]
This is the main reason to use tmux. Hope it gets into 3mux soon. Nice project btw.

**Comment by aaronjanse** [comment]
> Nice project btw.

Thanks!

@kafran session management is now available in 3mux `v1.0.0` :tada:

**Comment by kafran** [comment]
wow. nice. when I have time I'm gonna test it =)
its the same as tmux? ps, attach, etc...?

**Comment by aaronjanse** [comment]
It's `3mux ls` instead of `3mux ps`. I add an alias tonight. You should be able to manage your multiplexing via the interactive `3mux` command. It's fairly simple
