### ISSUE TITLE
scroll up should scroll content back

### ISSUE THREAD

**Issue by chinglinwen** [aaronjanse/3mux#55]
what happen

- scroll upward(scroll back),  show new content
- scroll downward(scroll down),  show old content

expect:

- scroll upward(scroll back),  show **old** content
- scroll downward(scroll down),  show **new** content

or provide a way to setting the mode.

version info:

- there's no version, build date is 2020-4-19 ( about newest build )

**Comment by aaronjanse** [comment]
I think I have this fixed in the `dev` branch for `v0.3.0`, which also adds config files.

In the morning, I'll check if 3mux is always the opposite of the OS default for scrolling. If so, I'll probably release a fix in `v0.2.2`.

Thanks for the bug report!

**Comment by aaronjanse** [comment]
Fixed in `v0.2.2`. Thanks for the bug report!

**Comment by chinglinwen** [comment]
Thank you!

**Comment by chinglinwen** [comment]
I've done verified the issue, and it's been fixed. it works great !
