### ISSUE TITLE
Scroll direction configurable

### ISSUE THREAD

**Issue by pepa65** [aaronjanse/3mux#58]
The way the scroll wheel moves through the output is opposite to how the scroll wheel works in other applications. Is there a way to configure this?

**Comment by aaronjanse** [comment]
> Is there a way to configure this?

Not yet, but 3mux today I'll test if 3mux changes based on system defaults. See #55 

Thanks for filing a bug report!

**Comment by aaronjanse** [comment]
> The way the scroll wheel moves through the output is opposite to how the scroll wheel works in other applications.

This is now fixed in `v0.2.2`.

> Is there a way to configure this?

Do you still think scrolling direction should be configurable, now that it matches the rest of the OS?

**Comment by pepa65** [comment]
Thanks! If it works as would be expected automagically, all the better..!
