### ISSUE TITLE
Not starting up

### ISSUE THREAD

**Issue by tinksabraham** [aaronjanse/3mux#59]
Error during: starting shell: fork/exec /usr/bin/zsh: invalid argument
Tiling state: Universe[0]()
goroutine 1 [running]:
runtime/debug.Stack(0x585280, 0xc000128008, 0xc00008dda8)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x9d
main.fatalShutdownNow(0xc000166000, 0x38)
        /home/z003ejhw/src/github.com/aaronjanse/3mux/main.go:133 +0x17e
main.newTerm(0x1, 0x562bd8)
        /home/z003ejhw/src/github.com/aaronjanse/3mux/pane.go:89 +0x270
main.main()
        /home/z003ejhw/src/github.com/aaronjanse/3mux/main.go:77 +0x2f9

**Comment by aaronjanse** [comment]
Would you mind telling me the output of the following commands?
```
ls -lah /usr/bin/zsh
```
```
echo $SHELL
```

**Comment by tinksabraham** [comment]
`ls -lah /usr/bin/zsh
- lrwxrwxrwx 1 root root 8 Mar  3 12:10 /usr/bin/zsh -> /bin/zsh
`

`
echo $SHELL
- /usr/bin/zsh
`

**Comment by aaronjanse** [comment]
In the meantime, I think `3mux` should work if you set `$SHELL` to `zsh`.

**Comment by tinksabraham** [comment]
I don't understand 
'$SHELL' is already assigned to 'zsh'

**Comment by aaronjanse** [comment]
> '$SHELL' is already assigned to 'zsh'

it's assigned to `/usr/bin/zsh`. Would you mind running `which zsh` to see where `zsh` points to in your `$PATH`?

**Comment by hgoldstein** [comment]
I'm running into this as well, but for me `3mux` just immediately exits:
```
$ 3mux -log
$ cat logs.txt
2020/04/22 19:15:57 exec: "zsh": executable file not found in $PATH
```

**Comment by aaronjanse** [comment]
> EDIT: I see this was fixed

Not sure. Could you provide me the output of `which zsh`?
Also, which OS are you using?

> I'm unable to `go get -u`

Weird. What's the output?

**Comment by hgoldstein** [comment]
> Not sure. Could you provide me the output of which zsh?

I don't have `zsh` installed so it's just blank:
```
$ which zsh
$
```

> Also, which OS are you using?

I'm running Ubuntu on WSL ... but yeah, no `zsh` so this makes sense.

> Weird. What's the output?

```
$ go get -u github.com/aaronjanse/3mux
# github.com/aaronjanse/3mux/ecma48
/home/hgoldstein/go/src/github.com/aaronjanse/3mux/ecma48/parser.go:331:26: syntax error: unexpected b001, expecting comma or }
/home/hgoldstein/go/src/github.com/aaronjanse/3mux/ecma48/parser.go:332:20: syntax error: unexpected ], expecting comma
or )
/home/hgoldstein/go/src/github.com/aaronjanse/3mux/ecma48/parser.go:334:7: syntax error: unexpected ) at end of statement
```

**Comment by aaronjanse** [comment]
> I don't have zsh installed so it's just blank:

Oh, I wonder why `3mux` is trying to launch `zsh`. Could you tell me the output of `$SHELL`?

Also, if you run `cat /etc/passwd | grep $USER`, you should see a shell after the last colon. Could you tell me what it is?

> [errors]

Oh, got it. It looks like older versions of golang don't support binary literals. I just pushed a commit to `master` that replaces the binary literals with normal integers. Would you mind trying `go get -u` again?

Thank you so much for the bug report and helping me debug!

**Comment by hgoldstein** [comment]
> I wonder why 3mux is trying to launch `zsh`.

I think what happened is that I had a particularly old version: must have tried to run it, ran into this, forgot about it, then came back to see the bug was still there.

```
$ echo $SHELL
/usr/bin/fish
```
Plus `/etc/passwd` says the same.

> Oh, got it. It looks like older versions of golang don't support binary literals

```
$  go version
go version go1.10.4 linux/amd64
```

I don't know `go` all that well so IDK if this is particularly old, but I wouldn't be surprised given I'm on Ubuntu 18.04.

Able to run `3mux` now :)

**Comment by aaronjanse** [comment]
> Able to run 3mux now :)

Oh, awesome. `3mux` is running `fish` now, right?

P.S.

**Comment by hgoldstein** [comment]
> ... 3mux is running fish now, right?

That it is!

**Comment by aaronjanse** [comment]
Awesome!

P.S. I recognize your GitHub account from when I was casually checking out ion a while ago :-)
