### ISSUE TITLE
Cannot select text

### ISSUE THREAD

**Issue by lpolzer-enercity** [aaronjanse/3mux#62]
It looks like I cannot select text with my mouse. Sorry if this is a duplicate, but I couldn't find anything like it.

Notion window manager. Text selection usually works fine.

**Comment by aaronjanse** [comment]
Not a duplicate. Thanks for the bug report!

Which termimal emulator do you use?

Also, have you tried pressing shift while selecting text?

**Comment by lpolzer-enercity** [comment]
Using xterm.

Yes, it works with Shift. Is that the intended behavior?

**Comment by aaronjanse** [comment]
> Yes, it works with Shift. Is that the intended behavior?

Sadly so. I might be wrong, but the only proper way I know of for capturing scrolling is by enabling mouse event capturing, which requires shift to be pressed if you select text.

If I find a terminal emulator that doesn't support shift to select, maybe I should add a keybinding to 3mux to temporarily disable mouse event capture.

**Comment by aaronjanse** [comment]
I'll close this for now. If anyone wants to explore further options, feel free to comment (and I'll re-open)
