### ISSUE TITLE
Binary release builds

### ISSUE THREAD

**Issue by arjvik** [aaronjanse/3mux#67]
Hi,

3mux looks really cool, and I would love to try it out. Unfortunately, I don't have a go toolchain setup, so I would rather download a single binary and run it. Would it be possible for you to upload the binary outputted by `go` into the github releases?

Thanks!

**Comment by aaronjanse** [comment]
This is a good idea. I'll try to get this done tomorrow evening.

**Comment by talentlessguy** [comment]
Probably [semantic-release](https://github.com/semantic-release/semantic-release) is worth trying

**Comment by aaronjanse** [comment]
Ooh, this looks interesting. I definitely want to automate the build process for releases.

**Comment by aaronjanse** [comment]
> This is a good idea. I'll try to get this done tomorrow evening.

Ahhh. I'm now aiming for this weekend for the sessions release :tada:

**Comment by kcthrn** [comment]
Build for ARM too please.

**Comment by talentlessguy** [comment]
@aaronjanse if you don't want to mess with JavaScript ecosystem, there's a [go rewrite](https://github.com/go-semantic-release/semantic-release).

**Comment by aaronjanse** [comment]
The latest release of `3mux` on Github now has pre-built binaries for `linux-amd64`, `linux-arm64`, and `darwin-amd64`.

@kcthrn I've used my Raspberry Pi to verify that the arm64 binary works (it does!)

**Comment by kcthrn** [comment]
@aaronjanse I have 32-bit ARM (armv7). I intend to run 3mux on Termux. Is 32-bit arm possible? Btw, thanks for the other binaries!

**Comment by aaronjanse** [comment]
@kcthrn would you mind checking if the attached binary works? If so, I'll add it to the `v1.0.0` release. Future release should have a 32-bit arm binary automatically built and attached.

[3mux-v1.0.0-linux-arm.tar.gz](https://github.com/aaronjanse/3mux/files/4675349/3mux-v1.0.0-linux-arm.tar.gz)

**Comment by kcthrn** [comment]
@aaronjanse In Termux I get this:
```
panic: open /tmp/3mux/: no such file or directory

goroutine 1 [running]:
main.defaultPrompt(0x0, 0x0, 0x0)
        /home/nixos/.go/src/github.com/aaronjanse/3mux/main.go:234 +0xf44
main.main()
        /home/nixos/.go/src/github.com/aaronjanse/3mux/main.go:121 +0x53c
```
Termux's tmp directory is actually `TMPDIR=/data/data/com.termux/files/usr/tmp`. I believe 3mux fails because the tmp directory may be hardcoded.

Wikipedia states for POSIX, the TMPDIR environment variable is used to set the system's temporary directory. Others include TEMP, TEMPDIR and TMP for non-POSIX OSs.

Source: https://en.wikipedia.org/wiki/TMPDIR

3mux does work in a PRoot environment (Alpine Linux) within Termux however.

**Comment by aaronjanse** [comment]
Whoa, 3mux within Termux is crazy cool!

I'll fix that tonight. Thanks for investigating.

**Comment by aaronjanse** [comment]
@kcthrn would you mind trying `v1.0.1`? It has an ARM binary on the releases page

**Comment by kcthrn** [comment]
@aaronjanse It works! Thank you!

**Comment by aaronjanse** [comment]
Yes!!!
