### ISSUE TITLE
connect: no such file or directory when trying to connect to an existing session

### ISSUE THREAD

**Issue by talentlessguy** [aaronjanse/3mux#69]
Here's what happens:

```
~ 
➜ 3mux
Attach to an existing session or create a new one:
> 3mux
+ create new session
```

I hit "Enter" and get this:

```
panic: dial unix /tmp/3mux/0/fd.sock: connect: no such file or directory

goroutine 1 [running]:
main.attach(0xc00001848b, 0x1)
        /home/v1rtl/go/src/github.com/aaronjanse/3mux/attach.go:36 +0x7c8
main.main()
        /home/v1rtl/go/src/github.com/aaronjanse/3mux/main.go:137 +0x695
```

I use v1.0.0 of 3mux and go1.14

**Comment by aaronjanse** [comment]
Would you mind telling me the exact steps to reproduce this, using the commands `3mux new`, `3mux detach`, and `3mux attach`?

**Comment by talentlessguy** [comment]
@aaronjanse the commands are:

```
3mux 
New session:
3mux

Ctrl + C
```

and then `3mux` again

**Comment by aaronjanse** [comment]
> Ctrl + C

Hmmm. Does `3mux` hang when you create a new session? If not, `ctrl+c` should not be possible.

Btw, which OS are you on?

**Comment by aaronjanse** [comment]
Oh, I just saw your other issue. You're running Linux. Stange

**Comment by talentlessguy** [comment]
@aaronjanse it does hang but in the background and fan starts to brrrrrrrrr so I later had to `kill` it.

I think that session handling is a bit buggy.

I'll try to create a session properly and open it and write if the issue persists.

**Comment by aaronjanse** [comment]
Oh wow, yeah, that definitely is not what's supposed to be happening. I'll try to reproduce it some time this week

**Comment by kcthrn** [comment]
I experienced this on Ubuntu 16.04, 20.04, Termux and Alpine PRoot in Termux. Seems like something to do with 3mux creating sessions when config.toml doesn't exist.
![issue-69](https://user-images.githubusercontent.com/16540129/82980685-14346b80-9fb8-11ea-8e31-7f04b60ef4dc.gif)

**Comment by kcthrn** [comment]
I noticed rogue `3mux _serve-id 0` processes using ~33% of CPU and ~540MB of memory. Probably from when 3mux had to be closed when it hang or restored a bad session.

**Comment by aaronjanse** [comment]
Ooooooohhhhh. Tysm! I'll work on a fix tomorrow. The GIF is perfect!

**Comment by aaronjanse** [comment]
It looks like I'll be quite busy for the next few days, so if anyone has the time to make a PR, please do.

I'd try inserting a `panic` statement in `config.go` and seeing what happens. If this intentional panic has the same effect as a missing config file, I'd look in `serve.go` to see why it's not handling errors properly.

Thank you, everyone, for being supportive and helpful as we work towards improving 3mux

**Comment by aaronjanse** [comment]
Oh, and for debugging purposes, the server can be launched with:
```bash
# wipe all sessions
pkill '3mux*' ; rm -rf /tmp/3mux

# start a session server
3mux _serve-id 0

# (in a different terminal) give the session a name then attach
echo test > /tmp/3mux/0/name
3mux attach test
```

I should document all of this
