### ISSUE TITLE
Use a latest spec compliant TOML implementation package

### ISSUE THREAD

**Issue by qlcom** [aaronjanse/3mux#90]

**Comment by qlcom** [comment]
the one currently being used does't support latest spec and its development has stopped

**Comment by aaronjanse** [comment]
This is still an issue. Thanks for filing a bug report. Would you (or someone else) mind making a small PR to fix the issue?

**Comment by qlcom** [comment]
currently there is only this package available github.com/pelletier/go-toml

should i use it?
